title: Jekyll VNG Realisatie theme

description: >-
   Jekyll version for VNG Realisatie

plugins:
  - jekyll-algolia
  - jekyll-remote-theme

markdown: kramdown

plugins:
  - jekyll-redirect-from

collections:
  pages:
    output: true
  content:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: ''
      type: content
    values:
      layout: default

sass:
  load_paths:
    - _sass

github: VNG-Realisatie/jekyll-theme-vng-realisatie
